// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "post_like/rpc_put_post_like.proto" (package "pb", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PostLike } from "./post_like";
import { LikeValue } from "./post_like";
/**
 * @generated from protobuf message pb.PutPostLikeRequest
 */
export interface PutPostLikeRequest {
    /**
     * @generated from protobuf field: string post_id = 1;
     */
    postId: string;
    /**
     * @generated from protobuf field: pb.LikeValue value = 2;
     */
    value: LikeValue;
}
/**
 * @generated from protobuf message pb.PutPostLikeResponse
 */
export interface PutPostLikeResponse {
    /**
     * @generated from protobuf field: pb.PostLike post_like = 1;
     */
    postLike?: PostLike;
}
// @generated message type with reflection information, may provide speed optimized methods
class PutPostLikeRequest$Type extends MessageType<PutPostLikeRequest> {
    constructor() {
        super("pb.PutPostLikeRequest", [
            { no: 1, name: "post_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "enum", T: () => ["pb.LikeValue", LikeValue] }
        ]);
    }
    create(value?: PartialMessage<PutPostLikeRequest>): PutPostLikeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.postId = "";
        message.value = 0;
        if (value !== undefined)
            reflectionMergePartial<PutPostLikeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutPostLikeRequest): PutPostLikeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string post_id */ 1:
                    message.postId = reader.string();
                    break;
                case /* pb.LikeValue value */ 2:
                    message.value = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutPostLikeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string post_id = 1; */
        if (message.postId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.postId);
        /* pb.LikeValue value = 2; */
        if (message.value !== 0)
            writer.tag(2, WireType.Varint).int32(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message pb.PutPostLikeRequest
 */
export const PutPostLikeRequest = new PutPostLikeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutPostLikeResponse$Type extends MessageType<PutPostLikeResponse> {
    constructor() {
        super("pb.PutPostLikeResponse", [
            { no: 1, name: "post_like", kind: "message", T: () => PostLike }
        ]);
    }
    create(value?: PartialMessage<PutPostLikeResponse>): PutPostLikeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PutPostLikeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutPostLikeResponse): PutPostLikeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* pb.PostLike post_like */ 1:
                    message.postLike = PostLike.internalBinaryRead(reader, reader.uint32(), options, message.postLike);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutPostLikeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* pb.PostLike post_like = 1; */
        if (message.postLike)
            PostLike.internalBinaryWrite(message.postLike, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message pb.PutPostLikeResponse
 */
export const PutPostLikeResponse = new PutPostLikeResponse$Type();
