// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "post_like/rpc_get_post_like.proto" (package "pb", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PostLike } from "./post_like";
/**
 * @generated from protobuf message pb.GetPostLikeRequest
 */
export interface GetPostLikeRequest {
    /**
     * @generated from protobuf field: string post_id = 1;
     */
    postId: string;
}
/**
 * @generated from protobuf message pb.GetPostLikeResponse
 */
export interface GetPostLikeResponse {
    /**
     * @generated from protobuf field: pb.PostLike post_like = 1;
     */
    postLike?: PostLike;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetPostLikeRequest$Type extends MessageType<GetPostLikeRequest> {
    constructor() {
        super("pb.GetPostLikeRequest", [
            { no: 1, name: "post_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPostLikeRequest>): GetPostLikeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.postId = "";
        if (value !== undefined)
            reflectionMergePartial<GetPostLikeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostLikeRequest): GetPostLikeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string post_id */ 1:
                    message.postId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostLikeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string post_id = 1; */
        if (message.postId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.postId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message pb.GetPostLikeRequest
 */
export const GetPostLikeRequest = new GetPostLikeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPostLikeResponse$Type extends MessageType<GetPostLikeResponse> {
    constructor() {
        super("pb.GetPostLikeResponse", [
            { no: 1, name: "post_like", kind: "message", T: () => PostLike }
        ]);
    }
    create(value?: PartialMessage<GetPostLikeResponse>): GetPostLikeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPostLikeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPostLikeResponse): GetPostLikeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* pb.PostLike post_like */ 1:
                    message.postLike = PostLike.internalBinaryRead(reader, reader.uint32(), options, message.postLike);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPostLikeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* pb.PostLike post_like = 1; */
        if (message.postLike)
            PostLike.internalBinaryWrite(message.postLike, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message pb.GetPostLikeResponse
 */
export const GetPostLikeResponse = new GetPostLikeResponse$Type();
