// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "post_like/service_post_like.proto" (package "pb", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PostLikeService } from "./service_post_like";
import type { Empty } from "../google/protobuf/empty";
import type { DeletePostLikeRequest } from "./rpc_delete_post_like";
import type { GetPostLikeResponse } from "./rpc_get_post_like";
import type { GetPostLikeRequest } from "./rpc_get_post_like";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PutPostLikeResponse } from "./rpc_put_post_like";
import type { PutPostLikeRequest } from "./rpc_put_post_like";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service pb.PostLikeService
 */
export interface IPostLikeServiceClient {
    /**
     * @generated from protobuf rpc: PutPostLike(pb.PutPostLikeRequest) returns (pb.PutPostLikeResponse);
     */
    putPostLike(input: PutPostLikeRequest, options?: RpcOptions): UnaryCall<PutPostLikeRequest, PutPostLikeResponse>;
    /**
     * @generated from protobuf rpc: GetPostLike(pb.GetPostLikeRequest) returns (pb.GetPostLikeResponse);
     */
    getPostLike(input: GetPostLikeRequest, options?: RpcOptions): UnaryCall<GetPostLikeRequest, GetPostLikeResponse>;
    /**
     * @generated from protobuf rpc: DeletePostLike(pb.DeletePostLikeRequest) returns (google.protobuf.Empty);
     */
    deletePostLike(input: DeletePostLikeRequest, options?: RpcOptions): UnaryCall<DeletePostLikeRequest, Empty>;
}
/**
 * @generated from protobuf service pb.PostLikeService
 */
export class PostLikeServiceClient implements IPostLikeServiceClient, ServiceInfo {
    typeName = PostLikeService.typeName;
    methods = PostLikeService.methods;
    options = PostLikeService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: PutPostLike(pb.PutPostLikeRequest) returns (pb.PutPostLikeResponse);
     */
    putPostLike(input: PutPostLikeRequest, options?: RpcOptions): UnaryCall<PutPostLikeRequest, PutPostLikeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PutPostLikeRequest, PutPostLikeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPostLike(pb.GetPostLikeRequest) returns (pb.GetPostLikeResponse);
     */
    getPostLike(input: GetPostLikeRequest, options?: RpcOptions): UnaryCall<GetPostLikeRequest, GetPostLikeResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostLikeRequest, GetPostLikeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePostLike(pb.DeletePostLikeRequest) returns (google.protobuf.Empty);
     */
    deletePostLike(input: DeletePostLikeRequest, options?: RpcOptions): UnaryCall<DeletePostLikeRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePostLikeRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
