// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "post_like/service_post_like.proto" (package "pb", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { DeletePostLikeRequest } from "./rpc_delete_post_like";
import { GetPostLikeResponse } from "./rpc_get_post_like";
import { GetPostLikeRequest } from "./rpc_get_post_like";
import { PutPostLikeResponse } from "./rpc_put_post_like";
import { PutPostLikeRequest } from "./rpc_put_post_like";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service pb.PostLikeService
 */
export const PostLikeService = new ServiceType("pb.PostLikeService", [
    { name: "PutPostLike", options: {}, I: PutPostLikeRequest, O: PutPostLikeResponse },
    { name: "GetPostLike", options: {}, I: GetPostLikeRequest, O: GetPostLikeResponse },
    { name: "DeletePostLike", options: {}, I: DeletePostLikeRequest, O: Empty }
]);
