// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "post/service_post.proto" (package "pb", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PostService } from "./service_post";
import type { Empty } from "../google/protobuf/empty";
import type { DeletePostRequest } from "./rpc_delete_post";
import type { UpdatePostResponse } from "./rpc_update_post";
import type { UpdatePostRequest } from "./rpc_update_post";
import type { GetPostsListingResponse } from "./rpc_get_posts_listing";
import type { GetPostsListingRequest } from "./rpc_get_posts_listing";
import type { GetPostResponse } from "./rpc_get_post";
import type { GetPostRequest } from "./rpc_get_post";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreatePostResponse } from "./rpc_create_post";
import type { CreatePostRequest } from "./rpc_create_post";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service pb.PostService
 */
export interface IPostServiceClient {
    /**
     * @generated from protobuf rpc: CreatePost(pb.CreatePostRequest) returns (pb.CreatePostResponse);
     */
    createPost(input: CreatePostRequest, options?: RpcOptions): UnaryCall<CreatePostRequest, CreatePostResponse>;
    /**
     * @generated from protobuf rpc: GetPost(pb.GetPostRequest) returns (pb.GetPostResponse);
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse>;
    /**
     * @generated from protobuf rpc: GetPostsListing(pb.GetPostsListingRequest) returns (pb.GetPostsListingResponse);
     */
    getPostsListing(input: GetPostsListingRequest, options?: RpcOptions): UnaryCall<GetPostsListingRequest, GetPostsListingResponse>;
    /**
     * @generated from protobuf rpc: UpdatePost(pb.UpdatePostRequest) returns (pb.UpdatePostResponse);
     */
    updatePost(input: UpdatePostRequest, options?: RpcOptions): UnaryCall<UpdatePostRequest, UpdatePostResponse>;
    /**
     * @generated from protobuf rpc: DeletePost(pb.DeletePostRequest) returns (google.protobuf.Empty);
     */
    deletePost(input: DeletePostRequest, options?: RpcOptions): UnaryCall<DeletePostRequest, Empty>;
}
/**
 * @generated from protobuf service pb.PostService
 */
export class PostServiceClient implements IPostServiceClient, ServiceInfo {
    typeName = PostService.typeName;
    methods = PostService.methods;
    options = PostService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePost(pb.CreatePostRequest) returns (pb.CreatePostResponse);
     */
    createPost(input: CreatePostRequest, options?: RpcOptions): UnaryCall<CreatePostRequest, CreatePostResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePostRequest, CreatePostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPost(pb.GetPostRequest) returns (pb.GetPostResponse);
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostRequest, GetPostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPostsListing(pb.GetPostsListingRequest) returns (pb.GetPostsListingResponse);
     */
    getPostsListing(input: GetPostsListingRequest, options?: RpcOptions): UnaryCall<GetPostsListingRequest, GetPostsListingResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostsListingRequest, GetPostsListingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePost(pb.UpdatePostRequest) returns (pb.UpdatePostResponse);
     */
    updatePost(input: UpdatePostRequest, options?: RpcOptions): UnaryCall<UpdatePostRequest, UpdatePostResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePostRequest, UpdatePostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePost(pb.DeletePostRequest) returns (google.protobuf.Empty);
     */
    deletePost(input: DeletePostRequest, options?: RpcOptions): UnaryCall<DeletePostRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePostRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
