// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "post/service_post.proto" (package "pb", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { DeletePostRequest } from "./rpc_delete_post";
import { UpdatePostResponse } from "./rpc_update_post";
import { UpdatePostRequest } from "./rpc_update_post";
import { GetPostsListingResponse } from "./rpc_get_posts_listing";
import { GetPostsListingRequest } from "./rpc_get_posts_listing";
import { GetPostResponse } from "./rpc_get_post";
import { GetPostRequest } from "./rpc_get_post";
import { CreatePostResponse } from "./rpc_create_post";
import { CreatePostRequest } from "./rpc_create_post";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service pb.PostService
 */
export const PostService = new ServiceType("pb.PostService", [
    { name: "CreatePost", options: {}, I: CreatePostRequest, O: CreatePostResponse },
    { name: "GetPost", options: {}, I: GetPostRequest, O: GetPostResponse },
    { name: "GetPostsListing", options: {}, I: GetPostsListingRequest, O: GetPostsListingResponse },
    { name: "UpdatePost", options: {}, I: UpdatePostRequest, O: UpdatePostResponse },
    { name: "DeletePost", options: {}, I: DeletePostRequest, O: Empty }
]);
