// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "user/service_user.proto" (package "pb", syntax proto3)
// tslint:disable
import { RefreshTokenResponse } from "./rpc_refresh_token";
import { RefreshTokenRequest } from "./rpc_refresh_token";
import { LoginUserResponse } from "./rpc_login_user";
import { LoginUserRequest } from "./rpc_login_user";
import { UpdateUserResponse } from "./rpc_update_user";
import { UpdateUserRequest } from "./rpc_update_user";
import { GetUserResponse } from "./rpc_get_user";
import { GetUserRequest } from "./rpc_get_user";
import { CreateUserResponse } from "./rpc_create_user";
import { CreateUserRequest } from "./rpc_create_user";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service pb.UserService
 */
export const UserService = new ServiceType("pb.UserService", [
    { name: "CreateUser", options: {}, I: CreateUserRequest, O: CreateUserResponse },
    { name: "GetUser", options: {}, I: GetUserRequest, O: GetUserResponse },
    { name: "UpdateUser", options: {}, I: UpdateUserRequest, O: UpdateUserResponse },
    { name: "LoginUser", options: {}, I: LoginUserRequest, O: LoginUserResponse },
    { name: "RefreshToken", options: {}, I: RefreshTokenRequest, O: RefreshTokenResponse }
]);
